### PR TITLE
PDF-to-HTML prototype

### PR DESCRIPTION
**Pull request by hbillings**
- Adds a `prototypes` folder to the repo so that we can create multiple prototypes for multiple hypotheses.
- Creates an outline of what the structure of an HTML page modeled on a current PDF could look like. (The content shown here is taken from HUD: https://www.hud.gov/sites/documents/2017_APP_2015_APR_FINAL.PDF) Note that this is NOT a complete report, and it is incredibly ugly at the moment. This is just meant to show possible document structure.

Screenshot:
screencapture-127-0-0-1-4000-agency-hud-1515717096720

### CODE REVIEW

**Comment by tram** [comment]
Sweet! Does it make sense for the blue line in the left nav to run the height of all the headers listed for that page? Basically down to the first horizontal line.

**Comment by AminPIC** [comment]
I think once the final "interim" site is built, that I a pull request should be issued to build this in. Thoughts?

**Comment by adborden** [comment]
On Thu, 2018-01-11 at 05:57 -0800, AminPIC <notifications@github.com> wrote:
> I think once the final "interim" site is built, that I a pull request should be issued to build this in. Thoughts?

Do you mean that once the interim site is up that we incorporate this PR
into the interim site? I'm not sure that's necessary. This will be
helpful to run some experiements, but I think we'll throw it away once
we've used it up. I'd rather not tie it up with the interim site which
is meant to be a production setup where this is really just a temporary
thing.

--
Aaron D Borden
Human and hacker

**Comment by hbillings** [comment]
@tram Yeah, I think it would make sense to do that. I didn't mess with it for now because I don't want to spend too much time on one prototype, but if we want to test this structure with users, I definitely think that would justify doing some more visual work!

**Review by adborden — APPROVED** [review]

**Pull request merged**
